### PR TITLE
Fixes #14651 - Command for Arf report download

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
Works fine, one observation though, if I don't specify `--path` I'm getting following error

```sh
bin/hammer arf-report download --id 1675
Could not download the Arf report:
  Error: can't dup NilClass
```

Also it would be great if I got better error message if smart proxy is down, I'm getting this atm
```sh
Could not download the Arf report:
  Missing template api/v2/errors/ERF12-1731 [ProxyAPI::ProxyException]: Unable to get XML version of requested report from Smart Proxy ([Errno::ECONNREFUSED]: Connection refused - connect(2) for "foreman.example.tst" port 8443) for proxy https://foreman.example.tst:8443/compliance with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rabl]}. Searched in:
    * "/home/ares/Projekty/Zdrojaky/foreman/app/views"
    * "/home/ares/Projekty/Zdrojaky/foreman_discovery/app/views"
    * "/home/ares/Projekty/Zdrojaky/foreman_ansible/app/views"
    * "/home/ares/Projekty/Zdrojaky/foreman_remote_execution/app/views"
    * "/home/ares/Projekty/Zdrojaky/foreman-tasks/app/views"
    * "/home/ares/Projekty/Zdrojaky/foreman_openscap/app/views"
    * "/home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/apipie-rails-0.3.6/app/views"
```

although I'm not sure if this should be addressed in foreman_openscap API PR

other than that :clap:

**Comment by ares** [comment]
actually the issue when proxy is down is correct, the only confusing part is about missing template but all other important info is there, so just the empty `--path` deserves a fix :-)

**Comment by xprazak2** [comment]
I made a small cosmetic change here and updated [this](https://github.com/theforeman/foreman_openscap/pull/218) as well, you should get a pretty message when proxy is down.

**Comment by ares** [comment]
RfM :+1:

**Comment by ares** [comment]
Thanks @xprazak2, merged.

**Pull request merged**
