### PR TITLE
Rewrite workflow using reusable actions and add rubocop workflow.

### PR DESCRIPTION
**Pull request by archanaserver**
For reference: https://github.com/theforeman/hammer_cli_foreman_openscap/pull/47

### CODE REVIEW

**Comment by ehelms** [comment]
The gem does not currently require rubocop from what I can tell (you are adding it in https://github.com/theforeman/hammer_cli_foreman_openscap/pull/47). I would combine those two PRs together with separate commits so you can see that it runs.

**Comment by ofedoren** [comment]
https://github.com/theforeman/hammer_cli_foreman_openscap/pull/47 was merged, could you please rebase?

**Comment by ofedoren** [comment]
Since we're at it, could you please make the tests green by fixing the issues?

**Comment by ofedoren** [comment]
I think we don't need to test on Ruby < 2.7 anymore, could you please adjust?

**Comment by archanaserver** [comment]
@ofedoren fixed this here, thanks \o/

**Review by ofedoren — APPROVED** [review]
Thanks, @archanaserver, :rose:

**Pull request merged**
