### PR TITLE
Fixes #17633 - Add commands for tailoring files

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by tstrachota** [comment]
@ares the first failure seems to be mismatch between hammer core and plugin versions. Please check if you're not using hammer-cli-foreman < 0.9.0 and hammer-cli 0.9.0.

**Comment by shlomizadok** [comment]
@xprazak2 mind rebasing? (alos see notes from @ares and @tstrachota )

**Comment by xprazak2** [comment]
I rebased and added command for downloading xml file.

**Comment by ares** [comment]
Ok, updating works great now (could be caused by the mismatch) but still seeing 2 problems.

1) if I don't specify `--original-filename` and try to create new tailoring file

```
hammer tailoring-file create --name new-active --scap-file ~/z/foreman/tmp/ssg-centos7-ds-tailoring.xml

Failed to create Tailoring file:
  ERROR:  null value in column "original_filename" violates not-null constraint
  DETAIL:  Failing row contains (12, new-active, <?xml version="1.0" encoding="UTF-8"?>
  <xccdf:Tailoring xmlns:xc..., null, 2017-03-02 12:09:04.92901, 2017-03-02 12:09:04.92901, 4f4519c40d33fe21f137d0ea831dd8c5da71b7950446f4275b60c2a3c0d0bdce).
```

Can't we just get it from the `$scap_file` parameter by `File.basename($scap_file)` if user does not provide value?

2) Downloading does not seem to work for me, here's the full run with --debug

```
ares@tony:[~/z/hammer][master✓]$ hammer --debug tailoring-file download --id 11
[ INFO 2017-03-02T13:13:50 Init] Initialization of Hammer CLI (0.9.0) has started...
[DEBUG 2017-03-02T13:13:50 Init] Running at ruby 2.2.2-p95
[ INFO 2017-03-02T13:13:50 Init] Configuration from the file /home/ares/.hammer/cli_config.yml has been loaded
[ WARN 2017-03-02T13:13:50 Modules] Legacy configuration of modules detected. Check section about configuration in user manual
[DEBUG 2017-03-02T13:13:50 API] Global headers: {
        :content_type => "application/json",
              :accept => "application/json;version=2",
    "Accept-Language" => "cs"
}
[DEBUG 2017-03-02T13:13:50 API] Follow redirects: never
[DEBUG 2017-03-02T13:13:50 Connection] Registered: foreman
[ INFO 2017-03-02T13:13:50 Modules] Extension module hammer_cli_foreman (0.9.0) loaded
[ INFO 2017-03-02T13:13:50 Modules] Extension module hammer_cli_foreman_discovery (0.0.2) loaded
[ INFO 2017-03-02T13:13:50 Modules] Extension module hammer_cli_foreman_openscap (0.1.2) loaded
[ INFO 2017-03-02T13:13:50 Modules] Extension module hammer_cli_foreman_remote_execution (0.0.2) loaded
[DEBUG 2017-03-02T13:13:50 Init] Using locale 'cs'
[DEBUG 2017-03-02T13:13:50 Init] 'mo' files for locale domain 'hammer-cli' loaded from '/home/ares/Projekty/Zdrojaky/hammer-cli/locale'
[DEBUG 2017-03-02T13:13:50 Init] 'mo' files for locale domain 'hammer-cli-foreman' loaded from '/home/ares/Projekty/Zdrojaky/hammer-cli-foreman/locale'
[ INFO 2017-03-02T13:13:50 HammerCLI::MainCommand] Called with options: {"option_debug"=>true}
[ INFO 2017-03-02T13:13:50 HammerCLIForemanOpenscap::TailoringFile] Called with options: {}
[ INFO 2017-03-02T13:13:50 HammerCLIForemanOpenscap::TailoringFile::DownloadCommand] Called with options: {"option_id"=>"11"}
[ INFO 2017-03-02T13:13:50 API] Server: https://foreman.example.tst
[ INFO 2017-03-02T13:13:50 API] GET /api/compliance/tailoring_files/11/xml
[DEBUG 2017-03-02T13:13:50 API] Params: {}
[DEBUG 2017-03-02T13:13:50 API] Headers: {
    :params => {}
}
[DEBUG 2017-03-02T13:13:50 API] Using authenticator: HammerCLIForeman::Api::SessionAuthenticatorWrapper
[DEBUG 2017-03-02T13:13:51 API] Response: <RestClient::Response 200 "<?xml versi...">
[DEBUG 2017-03-02T13:13:51 API] Response headers: {
                               :server => "nginx/1.10.2",
                                 :date => "Thu, 02 Mar 2017 12:13:51 GMT",
                         :content_type => "application/xml",
                    :transfer_encoding => "chunked",
                           :connection => "keep-alive",
                               :status => "200 OK",
                        :cache_control => "private",
            :strict_transport_security => "max-age=631152000; includeSubdomains",
    :x_permitted_cross_domain_policies => "none",
                     :x_xss_protection => "1; mode=block",
                         :x_request_id => "8b7523d3-cdb5-4254-be5a-fafcc88e0f34",
                  :content_disposition => "attachment; filename=\"ssg-centos7-ds-tailoring.xml\"",
                   :x_download_options => "noopen",
            :content_transfer_encoding => "binary",
                                 :etag => "W/\"5d0c595af58a3e1a3bb3127d9a36ab5c\"",
                            :x_runtime => "0.049408",
                      :foreman_version => "1.15.0-develop",
                  :foreman_api_version => "2",
                      :apipie_checksum => "9a61771793dba1418303283481b9cb96",
              :content_security_policy => "default-src 'self'; child-src 'self'; connect-src 'self' ws: wss:; img-src 'self' data: *.gravatar.com; script-src 'unsafe-eval' 'unsafe-inline' 'self'; style-src 'unsafe-inline' 'self'",
               :x_content_type_options => "nosniff",
                      :x_frame_options => "sameorigin",
                         :x_powered_by => "Phusion Passenger 5.1.2",
                     :content_encoding => "gzip"
}
[ERROR 2017-03-02T13:13:51 Exception] Error: can't dup NilClass
Could not download the Tailoring file:
  Error: can't dup NilClass
[ERROR 2017-03-02T13:13:51 Exception] 

TypeError (can't dup NilClass):
    /home/ares/Projekty/Zdrojaky/hammer_cli_foreman_openscap/lib/hammer_cli_foreman_openscap/commands.rb:57:in `dup'
    /home/ares/Projekty/Zdrojaky/hammer_cli_foreman_openscap/lib/hammer_cli_foreman_openscap/commands.rb:57:in `print_data'
    /home/ares/Projekty/Zdrojaky/hammer-cli/lib/hammer_cli/apipie/command.rb:35:in `execute'
    /home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
    /home/ares/Projekty/Zdrojaky/hammer-cli/lib/hammer_cli/abstract.rb:24:in `run'
    /home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
    /home/ares/Projekty/Zdrojaky/hammer-cli/lib/hammer_cli/abstract.rb:24:in `run'
    /home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
    /home/ares/Projekty/Zdrojaky/hammer-cli/lib/hammer_cli/abstract.rb:24:in `run'
    /home/ares/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
    bin/hammer:125:in `<main>'
```

**Comment by ares** [comment]
The second problem happens if I don't specify the path. I think we should print nicer error, that path is required. Also the help should mention it's the directory where the file will be downloaded to, now it's not clear whether the path should or should not contain the file name.

**Comment by ares** [comment]
Other that that works fine (tested with https://github.com/theforeman/foreman_openscap/pull/241 which needs to get in first)

**Comment by xprazak2** [comment]
Path is now required by validation and a nice message is printed, also the help message is improved.

**Comment by ares** [comment]
That part works nice, is there something we could do with issue 1) I mentioned above?

**Comment by xprazak2** [comment]
Issue 1) should be solved now - when original file name is not supplied by user as an option, it is detected from uploaded file.

**Comment by ares** [comment]
Thanks @xprazak2, works nicely! Merging.

**Pull request merged**
