### PR TITLE
Fixes #20671 - Show hostgroups in policy info command

### PR DESCRIPTION
**Pull request by xprazak2**
needs changes in [rabl](https://github.com/theforeman/foreman_openscap/pull/281) template

### CODE REVIEW

**Comment by ares** [comment]
could you please rebase?

**Comment by ares** [comment]
otherwise works well

**Comment by xprazak2** [comment]
Rebased.

**Comment by ares** [comment]
Thanks @xprazak2, merging.

**Comment by ares** [comment]
I should have checked the ticket number, please avoid using the same ticket for multiple repos, we can't track the release version in redmine.

**Pull request merged**
