### PR TITLE
Remove OVAL mentions

### PR DESCRIPTION
**Pull request by ofedoren**
I hope Ondřej Pražák won't punch me for destroying his work :D

I've included here i18n update to remove some lines from the `.pot` file.

### CODE REVIEW

**Comment by xprazak2** [comment]
LGTM :D

**Comment by ofedoren** [comment]
@adamruzicka, can I get your blessing here as well? :)

**Review by adamruzicka — APPROVED** [review]
Yes, sure, let's make things more lean. Thank you

**Comment by adamruzicka** [comment]
Thank you @ofedoren & @xprazak2 !

**Pull request merged**
