### PR TITLE
Fixes #18659 - Command for report download in HTML

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
I'm getting the same issue issue as in #6 if the --path is not specified. Other that that works fine (tested with theforeman/foreman_openscap#241 which needs to get in first)

**Comment by xprazak2** [comment]
I added the path option validation which should take care of the problem for all download commands.

**Comment by ares** [comment]
@xprazak2 could the command print the path to the file? I can't easily tell if I already have some report files in directory where I download the new one. I can confirm that path is now properly validated.

**Comment by xprazak2** [comment]
Success message will now print full path to the downloaded file.

**Comment by ares** [comment]
Works nicely, thanks @xprazak2, merging.

**Pull request merged**
