### PR TITLE
Add theforeman-rubocop gem and Rubocop configuration

### PR DESCRIPTION
**Pull request by archanaserver**
Added theforeman-rubocop gem to v0.1.0 and the rubocop configuration, followed by lenient style from the gem.

### CODE REVIEW

**Comment by ofedoren** [comment]
This doesn't seem to be used anywhere in tests, do we want that? E.g. in the github workflow.

**Comment by archanaserver** [comment]
> This doesn't seem to be used anywhere in tests, do we want that? E.g. in the github workflow.

I guess this need a workflow for rubocop as well. I'll try adding it. Thanks @ofedoren

**Comment by archanaserver** [comment]
@ofedoren I have tried adding workflow for the same, would you please take a look why it's not passing it? https://github.com/theforeman/hammer_cli_foreman_openscap/pull/49

**Review by ofedoren — APPROVED** [review]
Thanks, @archanaserver, let's get this in.

**Pull request merged**
