### PR TITLE
Fixes #21638 - Add 'policy hosts' subcommand

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Needs changes in [hammer-cli-foreman](https://github.com/theforeman/hammer-cli-foreman/pull/342) to work.

**Comment by ofedoren** [comment]
@xprazak2, works as expected. https://github.com/theforeman/hammer-cli-foreman/pull/342 is merged, so if you've got nothing to add/change in this PR, I'll help you and merge it :)

**Comment by xprazak2** [comment]
I am glad it works, I have nothing else to add :)

**Comment by ofedoren** [comment]
@xprazak2, merging then.

**Pull request merged**
